-- ============================================================
-- Focus World Cup Pool — full schema setup for a NEW Supabase project
-- Generated by concatenating supabase/migrations/* in order.
-- Paste this whole file into your new project's SQL Editor and Run.
-- ============================================================


-- ============================================================
-- migration: 20260605064226_5a85ed40-8d58-404d-855c-9e780536a264.sql
-- ============================================================

-- Roles enum + table
CREATE TYPE public.app_role AS ENUM ('admin', 'member');

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role app_role NOT NULL DEFAULT 'member',
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;

CREATE POLICY "users see own roles" ON public.user_roles FOR SELECT TO authenticated USING (auth.uid() = user_id);

-- Profiles
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text NOT NULL,
  avatar_url text,
  payment_status text NOT NULL DEFAULT 'pending', -- pending | paid
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.profiles TO authenticated;
GRANT INSERT, UPDATE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles readable by authenticated" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "users update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "users insert own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

-- Teams
CREATE TABLE public.teams (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  code text NOT NULL UNIQUE,
  flag_emoji text NOT NULL,
  coach text,
  fifa_rank int,
  group_name text,
  squad text[] DEFAULT '{}',
  wc_form text,
  is_eliminated boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.teams TO authenticated, anon;
GRANT ALL ON public.teams TO service_role;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
CREATE POLICY "teams public read" ON public.teams FOR SELECT USING (true);

-- Matches
CREATE TABLE public.matches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_a_id uuid REFERENCES public.teams(id) ON DELETE SET NULL,
  team_b_id uuid REFERENCES public.teams(id) ON DELETE SET NULL,
  kickoff_utc timestamptz NOT NULL,
  stage text NOT NULL DEFAULT 'group', -- group | r32 | r16 | qf | sf | final
  group_name text,
  venue text,
  score_a int,
  score_b int,
  status text NOT NULL DEFAULT 'scheduled', -- scheduled | live | finished
  winner_team_id uuid REFERENCES public.teams(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.matches TO authenticated, anon;
GRANT ALL ON public.matches TO service_role;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "matches public read" ON public.matches FOR SELECT USING (true);

-- Bets
CREATE TABLE public.bets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  team_id uuid NOT NULL REFERENCES public.teams(id) ON DELETE RESTRICT,
  entry_fee numeric NOT NULL DEFAULT 1000,
  points int NOT NULL DEFAULT 0,
  placed_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.bets TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.bets TO authenticated;
GRANT ALL ON public.bets TO service_role;
ALTER TABLE public.bets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "bets readable by authenticated" ON public.bets FOR SELECT TO authenticated USING (true);
CREATE POLICY "users manage own bet" ON public.bets FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Quiz
CREATE TYPE public.quiz_tier AS ENUM ('beginner', 'professional', 'expertise');

CREATE TABLE public.quiz_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tier quiz_tier NOT NULL,
  question text NOT NULL,
  options jsonb NOT NULL, -- ["A","B","C","D"]
  correct_index int NOT NULL,
  explanation text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.quiz_questions TO authenticated;
GRANT ALL ON public.quiz_questions TO service_role;
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "quiz readable by authenticated" ON public.quiz_questions FOR SELECT TO authenticated USING (true);

CREATE TABLE public.quiz_progress (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  question_id uuid NOT NULL REFERENCES public.quiz_questions(id) ON DELETE CASCADE,
  correct boolean NOT NULL,
  answered_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, question_id)
);
GRANT SELECT, INSERT ON public.quiz_progress TO authenticated;
GRANT ALL ON public.quiz_progress TO service_role;
ALTER TABLE public.quiz_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "users see own progress" ON public.quiz_progress FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "users insert own progress" ON public.quiz_progress FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Trivia facts
CREATE TABLE public.trivia_facts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.trivia_facts TO authenticated, anon;
GRANT ALL ON public.trivia_facts TO service_role;
ALTER TABLE public.trivia_facts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "trivia public read" ON public.trivia_facts FOR SELECT USING (true);

-- Auto-create profile + member role on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'display_name', NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'member');
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- updated_at trigger
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

CREATE TRIGGER profiles_touch BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();


-- ============================================================
-- migration: 20260605064249_cce85d95-74ce-4d22-a506-563f58509d9f.sql
-- ============================================================

ALTER FUNCTION public.touch_updated_at() SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.touch_updated_at() FROM PUBLIC, anon, authenticated;


-- ============================================================
-- migration: 20260605064311_220e73f3-4a04-4cd5-af97-4b26e5569cbf.sql
-- ============================================================
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM authenticated;

-- ============================================================
-- migration: 20260606155153_f4a1466d-648c-4a63-8c94-c41202b5be45.sql
-- ============================================================

-- Add time_tbc column for matches without confirmed kickoff time
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS time_tbc BOOLEAN NOT NULL DEFAULT false;

-- Wipe dependent data (old wrong teams/matches/bets)
DELETE FROM public.quiz_progress;
DELETE FROM public.bets;
DELETE FROM public.matches;
DELETE FROM public.teams;

-- Insert 48 confirmed teams in 12 groups (A-L)
INSERT INTO public.teams (code, name, flag_emoji, group_name, fifa_rank, coach, wc_form, squad) VALUES
('MEX','Mexico','🇲🇽','A',18,'Javier Aguirre','Co-host. 17 WC appearances; best finish QF (1970, 1986).','{}'),
('KOR','South Korea','🇰🇷','A',23,'Hong Myung-bo','11 WCs; semi-final 2002.','{}'),
('RSA','South Africa','🇿🇦','A',56,'TBC','3rd WC; hosted 2010.','{}'),
('CZE','Czechia','🇨🇿','A',42,'Ivan Hašek','Returning to the WC.','{}'),
('CAN','Canada','🇨🇦','B',47,'Jesse Marsch','Co-host. 3rd WC.','{}'),
('SUI','Switzerland','🇨🇭','B',20,'Murat Yakin','12 WCs; R16 in 2014, 2018, 2022.','{}'),
('QAT','Qatar','🇶🇦','B',54,'TBC','2nd WC; hosted 2022.','{}'),
('BIH','Bosnia and Herzegovina','🇧🇦','B',74,'Sergej Barbarez','2nd WC (debut 2014).','{}'),
('BRA','Brazil','🇧🇷','C',5,'Carlo Ancelotti','5× champions (1958, 62, 70, 94, 02). Only nation at every WC.','{}'),
('MAR','Morocco','🇲🇦','C',14,'Walid Regragui','Semi-final 2022 — first African nation.','{}'),
('SCO','Scotland','🏴󠁧󠁢󠁳󠁣󠁴󠁿','C',39,'Steve Clarke','First WC since 1998.','{}'),
('HAI','Haiti','🇭🇹','C',83,'TBC','2nd WC; first since 1974.','{}'),
('USA','United States','🇺🇸','D',16,'Mauricio Pochettino','Co-host. 11 WCs; semi-final 1930.','{}'),
('PAR','Paraguay','🇵🇾','D',37,'Gustavo Alfaro','9th WC; QF in 2010.','{}'),
('AUS','Australia','🇦🇺','D',26,'Tony Popovic','7th WC; R16 in 2006 & 2022.','{}'),
('TUR','Türkiye','🇹🇷','D',26,'Vincenzo Montella','Returning to the WC; 3rd place 2002.','{}'),
('GER','Germany','🇩🇪','E',9,'Julian Nagelsmann','4× champions (1954, 74, 90, 2014).','{}'),
('ECU','Ecuador','🇪🇨','E',32,'Sebastián Beccacece','5th WC.','{}'),
('CIV','Ivory Coast','🇨🇮','E',41,'Emerse Faé','4th WC.','{}'),
('CUW','Curaçao','🇨🇼','E',82,'Dick Advocaat','WC debut.','{}'),
('NED','Netherlands','🇳🇱','F',7,'Ronald Koeman','11 WCs; 3× runners-up.','{}'),
('JPN','Japan','🇯🇵','F',17,'Hajime Moriyasu','8th WC; R16 in 2002, 10, 18, 22.','{}'),
('TUN','Tunisia','🇹🇳','F',45,'Sami Trabelsi','7th WC.','{}'),
('SWE','Sweden','🇸🇪','F',43,'TBC','13 WCs; runners-up 1958.','{}'),
('BEL','Belgium','🇧🇪','G',8,'Rudi Garcia','14 WCs; 3rd place 2018.','{}'),
('EGY','Egypt','🇪🇬','G',36,'Hossam Hassan','4th WC.','{}'),
('IRN','Iran','🇮🇷','G',23,'Amir Ghalenoei','7th WC.','{}'),
('NZL','New Zealand','🇳🇿','G',86,'Darren Bazeley','3rd WC.','{}'),
('ESP','Spain','🇪🇸','H',3,'Luis de la Fuente','Champions 2010. 16 WCs.','{}'),
('URU','Uruguay','🇺🇾','H',13,'Marcelo Bielsa','2× champions (1930, 1950). 15 WCs.','{}'),
('KSA','Saudi Arabia','🇸🇦','H',58,'Hervé Renard','7th WC.','{}'),
('CPV','Cape Verde','🇨🇻','H',70,'Bubista','WC debut.','{}'),
('FRA','France','🇫🇷','I',2,'Didier Deschamps','2× champions (1998, 2018). 16 WCs.','{}'),
('SEN','Senegal','🇸🇳','I',19,'Pape Thiaw','4th WC; R16 in 2002 & 2022.','{}'),
('NOR','Norway','🇳🇴','I',38,'Ståle Solbakken','First WC since 1998.','{}'),
('IRQ','Iraq','🇮🇶','I',57,'Graham Arnold','First WC since 1986.','{}'),
('ARG','Argentina','🇦🇷','J',1,'Lionel Scaloni','Defending champions (2022). 3× champions (1978, 86, 2022).','{}'),
('AUT','Austria','🇦🇹','J',24,'Ralf Rangnick','8th WC.','{}'),
('ALG','Algeria','🇩🇿','J',34,'Vladimir Petković','5th WC.','{}'),
('JOR','Jordan','🇯🇴','J',64,'Jamal Sellami','WC debut.','{}'),
('POR','Portugal','🇵🇹','K',6,'Roberto Martínez','8th WC; semi-final 1966 & 2006.','{}'),
('COL','Colombia','🇨🇴','K',12,'Néstor Lorenzo','7th WC.','{}'),
('UZB','Uzbekistan','🇺🇿','K',57,'Timur Kapadze','WC debut.','{}'),
('COD','DR Congo','🇨🇩','K',55,'Sébastien Desabre','3rd WC.','{}'),
('ENG','England','🏴󠁧󠁢󠁥󠁮󠁧󠁿','L',4,'Thomas Tuchel','Champions 1966. 16 WCs.','{}'),
('CRO','Croatia','🇭🇷','L',11,'Zlatko Dalić','Runners-up 2018; 3rd 2022.','{}'),
('GHA','Ghana','🇬🇭','L',73,'Otto Addo','5th WC; QF 2010.','{}'),
('PAN','Panama','🇵🇦','L',46,'Thomas Christiansen','2nd WC.','{}');

-- Generate 72 group-stage match slots (round-robin per group, all marked TBC except 4 confirmed below)
DO $$
DECLARE
  g TEXT;
  groups TEXT[] := ARRAY['A','B','C','D','E','F','G','H','I','J','K','L'];
  team_ids UUID[];
  pairs INT[][] := ARRAY[[1,2],[3,4],[1,3],[2,4],[1,4],[2,3]];
  p INT[];
  default_kick TIMESTAMPTZ := '2026-06-20 12:00:00+00';
BEGIN
  FOREACH g IN ARRAY groups LOOP
    SELECT array_agg(id ORDER BY code) INTO team_ids FROM public.teams WHERE group_name = g;
    FOREACH p SLICE 1 IN ARRAY pairs LOOP
      INSERT INTO public.matches (team_a_id, team_b_id, group_name, stage, kickoff_utc, status, time_tbc, venue)
      VALUES (team_ids[p[1]], team_ids[p[2]], g, 'group', default_kick, 'scheduled', true, NULL);
    END LOOP;
  END LOOP;
END $$;

-- Confirmed opening fixtures (NPT = UTC + 5:45)
UPDATE public.matches SET kickoff_utc='2026-06-11 19:00:00+00', time_tbc=false, venue='Estadio Azteca, Mexico City'
WHERE stage='group' AND group_name='A'
  AND ((team_a_id=(SELECT id FROM teams WHERE code='MEX') AND team_b_id=(SELECT id FROM teams WHERE code='RSA'))
    OR (team_a_id=(SELECT id FROM teams WHERE code='RSA') AND team_b_id=(SELECT id FROM teams WHERE code='MEX')));

UPDATE public.matches SET kickoff_utc='2026-06-12 02:00:00+00', time_tbc=false, venue='Estadio Akron, Guadalajara'
WHERE stage='group' AND group_name='A'
  AND ((team_a_id=(SELECT id FROM teams WHERE code='KOR') AND team_b_id=(SELECT id FROM teams WHERE code='CZE'))
    OR (team_a_id=(SELECT id FROM teams WHERE code='CZE') AND team_b_id=(SELECT id FROM teams WHERE code='KOR')));

UPDATE public.matches SET kickoff_utc='2026-06-12 19:00:00+00', time_tbc=false, venue='BMO Field, Toronto'
WHERE stage='group' AND group_name='B'
  AND ((team_a_id=(SELECT id FROM teams WHERE code='CAN') AND team_b_id=(SELECT id FROM teams WHERE code='BIH'))
    OR (team_a_id=(SELECT id FROM teams WHERE code='BIH') AND team_b_id=(SELECT id FROM teams WHERE code='CAN')));

UPDATE public.matches SET kickoff_utc='2026-06-13 01:00:00+00', time_tbc=false, venue='SoFi Stadium, Los Angeles'
WHERE stage='group' AND group_name='D'
  AND ((team_a_id=(SELECT id FROM teams WHERE code='USA') AND team_b_id=(SELECT id FROM teams WHERE code='PAR'))
    OR (team_a_id=(SELECT id FROM teams WHERE code='PAR') AND team_b_id=(SELECT id FROM teams WHERE code='USA')));

-- Knockout placeholder slots (TBD teams, time TBC) = 32 matches → total 104
INSERT INTO public.matches (stage, kickoff_utc, status, time_tbc, venue)
SELECT 'r32', '2026-06-29 18:00:00+00', 'scheduled', true, NULL FROM generate_series(1,16);
INSERT INTO public.matches (stage, kickoff_utc, status, time_tbc, venue)
SELECT 'r16', '2026-07-05 18:00:00+00', 'scheduled', true, NULL FROM generate_series(1,8);
INSERT INTO public.matches (stage, kickoff_utc, status, time_tbc, venue)
SELECT 'qf', '2026-07-10 18:00:00+00', 'scheduled', true, NULL FROM generate_series(1,4);
INSERT INTO public.matches (stage, kickoff_utc, status, time_tbc, venue)
SELECT 'sf', '2026-07-14 18:00:00+00', 'scheduled', true, NULL FROM generate_series(1,2);
INSERT INTO public.matches (stage, kickoff_utc, status, time_tbc, venue)
VALUES ('third', '2026-07-18 18:00:00+00', 'scheduled', true, NULL);
INSERT INTO public.matches (stage, kickoff_utc, status, time_tbc, venue)
VALUES ('final', '2026-07-19 19:00:00+00', 'scheduled', true, 'MetLife Stadium, New York/New Jersey');


-- ============================================================
-- migration: 20260607124331_1f4ef8b7-5b04-4abd-8387-57bff6be5b3d.sql
-- ============================================================
-- Reseed matches with verified NPT schedule (stored as UTC)
DELETE FROM public.matches;
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-11T19:00:00.000Z', 'group', 'A', 'Estadio Azteca, Mexico City', false FROM public.teams ta, public.teams tb WHERE ta.code='MEX' AND tb.code='RSA';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-12T02:00:00.000Z', 'group', 'A', 'Estadio Akron, Guadalajara', false FROM public.teams ta, public.teams tb WHERE ta.code='KOR' AND tb.code='CZE';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-12T19:00:00.000Z', 'group', 'B', 'BMO Field, Toronto', false FROM public.teams ta, public.teams tb WHERE ta.code='CAN' AND tb.code='BIH';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-13T01:00:00.000Z', 'group', 'D', 'SoFi Stadium, Los Angeles', false FROM public.teams ta, public.teams tb WHERE ta.code='USA' AND tb.code='PAR';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-13T19:00:00.000Z', 'group', 'C', 'MetLife Stadium, New York/New Jersey', false FROM public.teams ta, public.teams tb WHERE ta.code='BRA' AND tb.code='MAR';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-13T22:00:00.000Z', 'group', 'D', 'BC Place, Vancouver', false FROM public.teams ta, public.teams tb WHERE ta.code='AUS' AND tb.code='TUR';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-14T01:00:00.000Z', 'group', 'C', 'Gillette Stadium, Boston', false FROM public.teams ta, public.teams tb WHERE ta.code='HAI' AND tb.code='SCO';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-14T04:00:00.000Z', 'group', 'B', 'Levi''s Stadium, San Francisco Bay', false FROM public.teams ta, public.teams tb WHERE ta.code='QAT' AND tb.code='SUI';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-14T17:00:00.000Z', 'group', 'E', 'NRG Stadium, Houston', false FROM public.teams ta, public.teams tb WHERE ta.code='GER' AND tb.code='CUW';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-14T20:00:00.000Z', 'group', 'F', 'AT&T Stadium, Dallas', false FROM public.teams ta, public.teams tb WHERE ta.code='NED' AND tb.code='JPN';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-14T23:00:00.000Z', 'group', 'E', 'Lincoln Financial Field, Philadelphia', false FROM public.teams ta, public.teams tb WHERE ta.code='CIV' AND tb.code='ECU';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-15T02:00:00.000Z', 'group', 'F', 'Estadio BBVA, Monterrey', false FROM public.teams ta, public.teams tb WHERE ta.code='SWE' AND tb.code='TUN';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-15T16:00:00.000Z', 'group', 'H', 'Mercedes-Benz Stadium, Atlanta', false FROM public.teams ta, public.teams tb WHERE ta.code='ESP' AND tb.code='CPV';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-15T19:00:00.000Z', 'group', 'G', 'Lumen Field, Seattle', false FROM public.teams ta, public.teams tb WHERE ta.code='BEL' AND tb.code='EGY';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-15T22:00:00.000Z', 'group', 'H', 'Hard Rock Stadium, Miami', false FROM public.teams ta, public.teams tb WHERE ta.code='KSA' AND tb.code='URU';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-16T01:00:00.000Z', 'group', 'G', 'SoFi Stadium, Los Angeles', false FROM public.teams ta, public.teams tb WHERE ta.code='IRN' AND tb.code='NZL';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-16T19:00:00.000Z', 'group', 'I', 'MetLife Stadium, New York/New Jersey', false FROM public.teams ta, public.teams tb WHERE ta.code='FRA' AND tb.code='SEN';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-16T22:00:00.000Z', 'group', 'I', 'Gillette Stadium, Boston', false FROM public.teams ta, public.teams tb WHERE ta.code='IRQ' AND tb.code='NOR';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-17T01:00:00.000Z', 'group', 'J', 'Arrowhead Stadium, Kansas City', false FROM public.teams ta, public.teams tb WHERE ta.code='ARG' AND tb.code='ALG';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-17T04:00:00.000Z', 'group', 'J', 'Levi''s Stadium, San Francisco Bay', false FROM public.teams ta, public.teams tb WHERE ta.code='AUT' AND tb.code='JOR';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-17T17:00:00.000Z', 'group', 'K', 'NRG Stadium, Houston', false FROM public.teams ta, public.teams tb WHERE ta.code='POR' AND tb.code='COD';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-17T20:00:00.000Z', 'group', 'L', 'AT&T Stadium, Dallas', false FROM public.teams ta, public.teams tb WHERE ta.code='ENG' AND tb.code='CRO';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-17T23:00:00.000Z', 'group', 'L', 'BMO Field, Toronto', false FROM public.teams ta, public.teams tb WHERE ta.code='GHA' AND tb.code='PAN';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-18T02:00:00.000Z', 'group', 'K', 'Estadio Azteca, Mexico City', false FROM public.teams ta, public.teams tb WHERE ta.code='UZB' AND tb.code='COL';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-18T16:00:00.000Z', 'group', 'A', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='CZE' AND tb.code='RSA';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-18T19:00:00.000Z', 'group', 'B', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='SUI' AND tb.code='BIH';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-18T22:00:00.000Z', 'group', 'B', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='CAN' AND tb.code='QAT';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-19T01:00:00.000Z', 'group', 'A', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='MEX' AND tb.code='KOR';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-19T19:00:00.000Z', 'group', 'D', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='USA' AND tb.code='AUS';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-19T22:00:00.000Z', 'group', 'C', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='SCO' AND tb.code='MAR';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-20T00:30:00.000Z', 'group', 'C', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='BRA' AND tb.code='HAI';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-20T03:00:00.000Z', 'group', 'D', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='TUR' AND tb.code='PAR';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-20T17:00:00.000Z', 'group', 'F', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='NED' AND tb.code='SWE';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-20T20:00:00.000Z', 'group', 'E', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='GER' AND tb.code='CIV';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-20T22:00:00.000Z', 'group', 'E', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='ECU' AND tb.code='CUW';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-21T04:00:00.000Z', 'group', 'F', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='TUN' AND tb.code='JPN';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-21T16:00:00.000Z', 'group', 'H', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='ESP' AND tb.code='KSA';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-21T21:00:00.000Z', 'group', 'G', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='BEL' AND tb.code='IRN';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-21T22:00:00.000Z', 'group', 'H', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='URU' AND tb.code='CPV';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-22T01:00:00.000Z', 'group', 'G', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='NZL' AND tb.code='EGY';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-22T21:00:00.000Z', 'group', 'I', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='FRA' AND tb.code='IRQ';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-23T00:00:00.000Z', 'group', 'I', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='NOR' AND tb.code='SEN';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-23T03:00:00.000Z', 'group', 'J', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='JOR' AND tb.code='ALG';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-23T17:00:00.000Z', 'group', 'K', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='POR' AND tb.code='UZB';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-23T20:00:00.000Z', 'group', 'L', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='ENG' AND tb.code='GHA';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-23T23:00:00.000Z', 'group', 'L', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='PAN' AND tb.code='CRO';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-24T02:00:00.000Z', 'group', 'K', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='COL' AND tb.code='COD';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-24T06:15:00.000Z', 'group', 'J', NULL, true FROM public.teams ta, public.teams tb WHERE ta.code='ARG' AND tb.code='AUT';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-24T19:00:00.000Z', 'group', 'B', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='SUI' AND tb.code='CAN';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-24T19:00:00.000Z', 'group', 'B', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='BIH' AND tb.code='QAT';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-24T22:00:00.000Z', 'group', 'C', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='MAR' AND tb.code='HAI';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-24T22:00:00.000Z', 'group', 'C', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='SCO' AND tb.code='BRA';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-25T01:00:00.000Z', 'group', 'A', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='RSA' AND tb.code='KOR';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-25T01:00:00.000Z', 'group', 'A', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='CZE' AND tb.code='MEX';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-25T20:00:00.000Z', 'group', 'E', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='CUW' AND tb.code='CIV';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-25T20:00:00.000Z', 'group', 'E', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='ECU' AND tb.code='GER';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-25T23:00:00.000Z', 'group', 'F', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='TUN' AND tb.code='NED';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-25T23:00:00.000Z', 'group', 'F', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='JPN' AND tb.code='SWE';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-26T02:00:00.000Z', 'group', 'D', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='TUR' AND tb.code='USA';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-26T02:00:00.000Z', 'group', 'D', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='PAR' AND tb.code='AUS';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-26T19:00:00.000Z', 'group', 'I', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='NOR' AND tb.code='FRA';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-26T19:00:00.000Z', 'group', 'I', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='SEN' AND tb.code='IRQ';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-27T00:00:00.000Z', 'group', 'H', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='CPV' AND tb.code='KSA';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-27T00:00:00.000Z', 'group', 'H', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='URU' AND tb.code='ESP';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-27T03:00:00.000Z', 'group', 'G', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='NZL' AND tb.code='BEL';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-27T03:00:00.000Z', 'group', 'G', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='EGY' AND tb.code='IRN';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-27T21:00:00.000Z', 'group', 'L', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='PAN' AND tb.code='ENG';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-27T21:00:00.000Z', 'group', 'L', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='CRO' AND tb.code='GHA';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-27T23:30:00.000Z', 'group', 'K', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='COL' AND tb.code='POR';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-27T23:30:00.000Z', 'group', 'K', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='COD' AND tb.code='UZB';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-28T02:00:00.000Z', 'group', 'J', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='ALG' AND tb.code='AUT';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) SELECT ta.id, tb.id, '2026-06-28T02:00:00.000Z', 'group', 'J', NULL, false FROM public.teams ta, public.teams tb WHERE ta.code='JOR' AND tb.code='ARG';
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-06-28T19:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-06-29T17:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-06-29T20:30:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-06-30T01:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-06-30T17:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-01T01:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-01T16:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-01T20:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-02T00:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-02T19:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-02T23:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-03T03:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-03T18:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-03T22:00:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-04T01:30:00.000Z', 'r32', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-04T06:15:00.000Z', 'r32', NULL, NULL, true);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-04T17:00:00.000Z', 'r16', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-04T21:00:00.000Z', 'r16', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-05T20:00:00.000Z', 'r16', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-06T00:00:00.000Z', 'r16', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-06T19:00:00.000Z', 'r16', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-07T00:00:00.000Z', 'r16', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-07T16:00:00.000Z', 'r16', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-07T20:00:00.000Z', 'r16', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-09T20:00:00.000Z', 'qf', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-10T19:00:00.000Z', 'qf', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-11T21:00:00.000Z', 'qf', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-12T01:00:00.000Z', 'qf', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-14T19:00:00.000Z', 'sf', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-15T19:00:00.000Z', 'sf', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-18T21:00:00.000Z', 'third', NULL, NULL, false);
INSERT INTO public.matches (team_a_id, team_b_id, kickoff_utc, stage, group_name, venue, time_tbc) VALUES (NULL, NULL, '2026-07-19T19:00:00.000Z', 'final', NULL, 'MetLife Stadium, New York/New Jersey', false);

DROP POLICY IF EXISTS "admins update any profile" ON public.profiles;
CREATE POLICY "admins update any profile" ON public.profiles
  FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS "admins see all roles" ON public.user_roles;
CREATE POLICY "admins see all roles" ON public.user_roles
  FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

-- ============================================================
-- migration: 20260608060249_67856b3c-80b5-4028-a0cd-e28c0f4a058b.sql
-- ============================================================

DROP POLICY IF EXISTS "bets readable by authenticated" ON public.bets;
CREATE POLICY "users see own bet" ON public.bets FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "admins see all bets" ON public.bets FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS "profiles readable by authenticated" ON public.profiles;
CREATE POLICY "users see own profile" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "admins see all profiles" ON public.profiles FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'));

CREATE OR REPLACE VIEW public.leaderboard_entries
WITH (security_invoker = false) AS
SELECT b.id AS bet_id, b.user_id, b.team_id, b.points, b.placed_at,
       p.display_name, p.avatar_url,
       t.name AS team_name, t.code AS team_code, t.flag_emoji AS team_flag_emoji
FROM public.bets b
LEFT JOIN public.profiles p ON p.id = b.user_id
LEFT JOIN public.teams t ON t.id = b.team_id;
GRANT SELECT ON public.leaderboard_entries TO authenticated;

CREATE OR REPLACE FUNCTION public.get_total_bet_count()
RETURNS integer LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT COUNT(*)::int FROM public.bets; $$;
GRANT EXECUTE ON FUNCTION public.get_total_bet_count() TO authenticated;

REVOKE SELECT ON public.quiz_questions FROM authenticated;
REVOKE SELECT ON public.quiz_questions FROM anon;
GRANT SELECT (id, tier, question, options, explanation, created_at) ON public.quiz_questions TO authenticated;

CREATE OR REPLACE FUNCTION public.submit_quiz_answer(p_question_id uuid, p_choice integer)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_correct_index integer; v_explanation text; v_is_correct boolean; v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  SELECT correct_index, explanation INTO v_correct_index, v_explanation
    FROM public.quiz_questions WHERE id = p_question_id;
  IF v_correct_index IS NULL THEN RAISE EXCEPTION 'Unknown question'; END IF;
  v_is_correct := (p_choice = v_correct_index);
  INSERT INTO public.quiz_progress (user_id, question_id, correct)
  VALUES (v_uid, p_question_id, v_is_correct)
  ON CONFLICT DO NOTHING;
  RETURN jsonb_build_object('correct', v_is_correct, 'correct_index', v_correct_index, 'explanation', v_explanation);
END;
$$;
GRANT EXECUTE ON FUNCTION public.submit_quiz_answer(uuid, integer) TO authenticated;


-- ============================================================
-- migration: 20260608060315_47acf9b8-3337-4ada-9cdb-dacdcf169a58.sql
-- ============================================================

REVOKE EXECUTE ON FUNCTION public.get_total_bet_count() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.submit_quiz_answer(uuid, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_total_bet_count() TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_quiz_answer(uuid, integer) TO authenticated;
REVOKE SELECT ON public.leaderboard_entries FROM PUBLIC, anon;
GRANT SELECT ON public.leaderboard_entries TO authenticated;


-- ============================================================
-- migration: 20260608081829_30cb4e61-7489-411b-a0ec-297a7bae7fa0.sql
-- ============================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON public.bets TO authenticated;
GRANT ALL ON public.bets TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;

GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;


-- ============================================================
-- migration: 20260608083011_92a78915-f0b2-4d5b-9ce1-846a11945e45.sql
-- ============================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bets TO authenticated;
GRANT ALL ON public.bets TO service_role;

-- ============================================================
-- migration: 20260608083912_d609ab43-b18a-4c81-b78e-9955e345d1fe.sql
-- ============================================================

GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.get_total_bet_count() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.submit_quiz_answer(uuid, integer) TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bets TO authenticated;
GRANT ALL ON public.bets TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;


-- ============================================================
-- migration: 20260609103127_f19b744c-7531-4f2a-a858-9d742237cddd.sql
-- ============================================================

-- 1. Recreate leaderboard_entries view with security_invoker
DROP VIEW IF EXISTS public.leaderboard_entries;
CREATE VIEW public.leaderboard_entries
WITH (security_invoker = true) AS
SELECT b.id AS bet_id,
       b.user_id,
       b.team_id,
       b.points,
       b.placed_at,
       p.display_name,
       p.avatar_url,
       t.name AS team_name,
       t.code AS team_code,
       t.flag_emoji AS team_flag_emoji
  FROM bets b
  LEFT JOIN profiles p ON p.id = b.user_id
  LEFT JOIN teams t ON t.id = b.team_id;
GRANT SELECT ON public.leaderboard_entries TO authenticated;
GRANT SELECT ON public.leaderboard_entries TO anon;

-- 2. Revoke EXECUTE on SECURITY DEFINER functions from PUBLIC and anon (keep authenticated/service_role)
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_total_bet_count() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.submit_quiz_answer(uuid, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_total_bet_count() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.submit_quiz_answer(uuid, integer) TO authenticated, service_role;

-- 3. Prevent users from updating their own payment_status via a trigger
CREATE OR REPLACE FUNCTION public.prevent_self_payment_status_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.payment_status IS DISTINCT FROM OLD.payment_status
     AND NOT public.has_role(auth.uid(), 'admin')
  THEN
    RAISE EXCEPTION 'payment_status can only be changed by admins';
  END IF;
  RETURN NEW;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.prevent_self_payment_status_change() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_prevent_self_payment_status ON public.profiles;
CREATE TRIGGER trg_prevent_self_payment_status
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.prevent_self_payment_status_change();

-- 4. Hide quiz_questions.correct_index from clients via column-level privileges.
REVOKE SELECT ON public.quiz_questions FROM authenticated, anon;
GRANT SELECT (id, tier, question, options, explanation, created_at)
  ON public.quiz_questions TO authenticated;
-- submit_quiz_answer (SECURITY DEFINER) is the only way to learn correct_index.


-- ============================================================
-- migration: 20260609103532_aa983d14-4d0e-42d6-8eec-b58a99e7c682.sql
-- ============================================================

-- =========================================================
-- 1. Bets: allow up to 3 picks per user, no duplicate teams
-- =========================================================
ALTER TABLE public.bets DROP CONSTRAINT IF EXISTS bets_user_id_key;
ALTER TABLE public.bets
  ADD CONSTRAINT bets_user_team_unique UNIQUE (user_id, team_id);

-- Cap at 3 picks per user via trigger (CHECK can't query rows).
CREATE OR REPLACE FUNCTION public.enforce_max_three_picks()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE c int;
BEGIN
  SELECT COUNT(*) INTO c FROM public.bets WHERE user_id = NEW.user_id;
  IF c >= 3 THEN
    RAISE EXCEPTION 'You may back at most 3 teams.';
  END IF;
  RETURN NEW;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.enforce_max_three_picks() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_enforce_max_three_picks ON public.bets;
CREATE TRIGGER trg_enforce_max_three_picks
BEFORE INSERT ON public.bets
FOR EACH ROW EXECUTE FUNCTION public.enforce_max_three_picks();

-- =========================================================
-- 2. Rebuild leaderboard_entries: one row per user with picks aggregated
-- =========================================================
DROP VIEW IF EXISTS public.leaderboard_entries;
CREATE VIEW public.leaderboard_entries
WITH (security_invoker = true) AS
SELECT
  p.id              AS user_id,
  p.display_name,
  p.avatar_url,
  COALESCE(SUM(b.points), 0)::int AS points,
  COUNT(b.id)::int   AS pick_count,
  MIN(b.placed_at)   AS first_placed_at,
  MAX(b.placed_at)   AS confirmed_at,
  COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'bet_id',     b.id,
        'team_id',    t.id,
        'team_name',  t.name,
        'team_code',  t.code,
        'team_flag_emoji', t.flag_emoji,
        'fifa_rank',  t.fifa_rank,
        'points',     b.points,
        'placed_at',  b.placed_at
      ) ORDER BY t.name
    ) FILTER (WHERE b.id IS NOT NULL),
    '[]'::jsonb
  ) AS picks
FROM public.profiles p
LEFT JOIN public.bets  b ON b.user_id = p.id
LEFT JOIN public.teams t ON t.id = b.team_id
GROUP BY p.id;
GRANT SELECT ON public.leaderboard_entries TO authenticated, anon;

-- =========================================================
-- 3. Daily quiz schema
-- =========================================================
ALTER TABLE public.quiz_questions ADD COLUMN IF NOT EXISTS last_used_on date;

CREATE TABLE IF NOT EXISTS public.daily_quizzes (
  quiz_date       date PRIMARY KEY,
  question_ids    uuid[] NOT NULL,
  trivia_fact_id  uuid REFERENCES public.trivia_facts(id),
  created_at      timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.daily_quizzes TO authenticated;
GRANT ALL ON public.daily_quizzes TO service_role;
ALTER TABLE public.daily_quizzes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "daily quizzes readable" ON public.daily_quizzes;
CREATE POLICY "daily quizzes readable" ON public.daily_quizzes
  FOR SELECT TO authenticated USING (true);

CREATE TABLE IF NOT EXISTS public.daily_quiz_attempts (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  quiz_date       date NOT NULL REFERENCES public.daily_quizzes(quiz_date) ON DELETE CASCADE,
  score           int  NOT NULL DEFAULT 0,
  total           int  NOT NULL DEFAULT 0,
  answers         jsonb NOT NULL DEFAULT '{}'::jsonb,
  completed_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, quiz_date)
);
GRANT SELECT, INSERT ON public.daily_quiz_attempts TO authenticated;
GRANT ALL ON public.daily_quiz_attempts TO service_role;
ALTER TABLE public.daily_quiz_attempts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "users see own attempts" ON public.daily_quiz_attempts;
CREATE POLICY "users see own attempts" ON public.daily_quiz_attempts
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "users insert own attempts" ON public.daily_quiz_attempts;
CREATE POLICY "users insert own attempts" ON public.daily_quiz_attempts
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- =========================================================
-- 4. Daily quiz helpers
--    Uses NPT (UTC+05:45) to compute "today".
-- =========================================================
CREATE OR REPLACE FUNCTION public.current_npt_date()
RETURNS date
LANGUAGE sql
STABLE
AS $$
  SELECT ((now() AT TIME ZONE 'UTC') + interval '5 hours 45 minutes')::date;
$$;

CREATE OR REPLACE FUNCTION public.get_daily_quiz()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_today date := public.current_npt_date();
  v_quiz  public.daily_quizzes%ROWTYPE;
  v_uid   uuid := auth.uid();
  v_qids  uuid[];
  v_fact  uuid;
  v_questions jsonb;
  v_attempt jsonb := NULL;
  v_streak int := 0;
  v_total_qs int;
  v_size int := 7;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

  SELECT * INTO v_quiz FROM public.daily_quizzes WHERE quiz_date = v_today;

  IF NOT FOUND THEN
    SELECT COUNT(*) INTO v_total_qs FROM public.quiz_questions;
    IF v_total_qs = 0 THEN
      RETURN jsonb_build_object('quiz_date', v_today, 'questions', '[]'::jsonb,
                                'trivia_fact', NULL, 'attempt', NULL, 'streak', 0);
    END IF;
    v_size := LEAST(v_size, v_total_qs);

    -- Prefer never-used; fall back to oldest last_used_on. Deterministic per day via seed.
    PERFORM setseed(
      ( (extract(epoch from v_today)::bigint % 100000)::float / 100000.0 )
    );

    SELECT array_agg(id) INTO v_qids FROM (
      SELECT id FROM public.quiz_questions
      ORDER BY last_used_on NULLS FIRST, random()
      LIMIT v_size
    ) s;

    SELECT id INTO v_fact FROM public.trivia_facts
      ORDER BY random() LIMIT 1;

    INSERT INTO public.daily_quizzes (quiz_date, question_ids, trivia_fact_id)
    VALUES (v_today, v_qids, v_fact)
    ON CONFLICT (quiz_date) DO NOTHING
    RETURNING * INTO v_quiz;

    IF v_quiz.quiz_date IS NULL THEN
      SELECT * INTO v_quiz FROM public.daily_quizzes WHERE quiz_date = v_today;
    END IF;

    UPDATE public.quiz_questions SET last_used_on = v_today WHERE id = ANY(v_quiz.question_ids);
  END IF;

  -- Build safe question payload (NO correct_index)
  SELECT jsonb_agg(jsonb_build_object(
    'id', q.id, 'question', q.question, 'options', q.options, 'tier', q.tier
  ) ORDER BY array_position(v_quiz.question_ids, q.id))
  INTO v_questions
  FROM public.quiz_questions q
  WHERE q.id = ANY(v_quiz.question_ids);

  SELECT to_jsonb(a) INTO v_attempt
    FROM public.daily_quiz_attempts a
    WHERE a.user_id = v_uid AND a.quiz_date = v_today;

  -- Simple streak: consecutive days up to and including yesterday with an attempt.
  WITH RECURSIVE days(d) AS (
    SELECT v_today - 1
    UNION ALL
    SELECT d - 1 FROM days
      WHERE EXISTS (SELECT 1 FROM public.daily_quiz_attempts
                    WHERE user_id = v_uid AND quiz_date = d)
      AND d > v_today - 60
  )
  SELECT COUNT(*) INTO v_streak FROM days
    WHERE EXISTS (SELECT 1 FROM public.daily_quiz_attempts
                  WHERE user_id = v_uid AND quiz_date = days.d);
  IF v_attempt IS NOT NULL THEN v_streak := v_streak + 1; END IF;

  RETURN jsonb_build_object(
    'quiz_date',  v_quiz.quiz_date,
    'questions',  COALESCE(v_questions, '[]'::jsonb),
    'trivia_fact', (SELECT to_jsonb(f) FROM public.trivia_facts f WHERE f.id = v_quiz.trivia_fact_id),
    'attempt',    v_attempt,
    'streak',     v_streak
  );
END;
$$;
REVOKE EXECUTE ON FUNCTION public.get_daily_quiz() FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.get_daily_quiz() TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.submit_daily_quiz_attempt(p_answers jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_today date := public.current_npt_date();
  v_quiz  public.daily_quizzes%ROWTYPE;
  v_uid   uuid := auth.uid();
  v_score int := 0;
  v_total int;
  v_qid   uuid;
  v_correct_index int;
  v_chosen int;
  v_breakdown jsonb := '[]'::jsonb;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

  SELECT * INTO v_quiz FROM public.daily_quizzes WHERE quiz_date = v_today;
  IF NOT FOUND THEN RAISE EXCEPTION 'No quiz for today yet'; END IF;

  IF EXISTS (SELECT 1 FROM public.daily_quiz_attempts WHERE user_id = v_uid AND quiz_date = v_today) THEN
    RAISE EXCEPTION 'You already attempted today''s quiz';
  END IF;

  v_total := array_length(v_quiz.question_ids, 1);
  FOREACH v_qid IN ARRAY v_quiz.question_ids LOOP
    SELECT correct_index INTO v_correct_index FROM public.quiz_questions WHERE id = v_qid;
    v_chosen := COALESCE((p_answers ->> v_qid::text)::int, -1);
    IF v_chosen = v_correct_index THEN v_score := v_score + 1; END IF;
    v_breakdown := v_breakdown || jsonb_build_object(
      'question_id', v_qid, 'chosen', v_chosen, 'correct_index', v_correct_index
    );
  END LOOP;

  INSERT INTO public.daily_quiz_attempts (user_id, quiz_date, score, total, answers)
  VALUES (v_uid, v_today, v_score, v_total, p_answers);

  RETURN jsonb_build_object('score', v_score, 'total', v_total, 'breakdown', v_breakdown);
END;
$$;
REVOKE EXECUTE ON FUNCTION public.submit_daily_quiz_attempt(jsonb) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.submit_daily_quiz_attempt(jsonb) TO authenticated, service_role;

REVOKE EXECUTE ON FUNCTION public.current_npt_date() FROM PUBLIC;


-- ============================================================
-- migration: 20260609103608_9af49fc2-4c8f-4242-9823-d97b791e537b.sql
-- ============================================================

CREATE OR REPLACE FUNCTION public.current_npt_date()
RETURNS date
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT ((now() AT TIME ZONE 'UTC') + interval '5 hours 45 minutes')::date;
$$;


-- ============================================================
-- migration: 20260610114433_3c145cfd-bad3-4de1-954f-fa05e42f4e02.sql
-- ============================================================

-- Allow authenticated users to see all bets (needed for leaderboard to show each user's teams)
CREATE POLICY "authenticated can view all bets"
  ON public.bets FOR SELECT TO authenticated USING (true);

-- Per-question quiz reveal: returns correct answer immediately after a selection
CREATE OR REPLACE FUNCTION public.reveal_daily_quiz_answer(p_question_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_today date := public.current_npt_date();
  v_quiz  public.daily_quizzes%ROWTYPE;
  v_correct_index int;
  v_explanation text;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  SELECT * INTO v_quiz FROM public.daily_quizzes WHERE quiz_date = v_today;
  IF NOT FOUND THEN RAISE EXCEPTION 'No quiz today'; END IF;
  IF NOT (p_question_id = ANY(v_quiz.question_ids)) THEN
    RAISE EXCEPTION 'Question not in today''s quiz';
  END IF;
  SELECT correct_index, explanation INTO v_correct_index, v_explanation
    FROM public.quiz_questions WHERE id = p_question_id;
  RETURN jsonb_build_object('correct_index', v_correct_index, 'explanation', v_explanation);
END;
$$;

REVOKE EXECUTE ON FUNCTION public.reveal_daily_quiz_answer(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reveal_daily_quiz_answer(uuid) TO authenticated;

